"""Static workflow event/problem registry.

The registry is a code-level contract between workflow event producers and
runtime consumers. It does not replace events.jsonl truth or zf.yaml control
plane; it only classifies emitted events so Supervisor, Run Manager, and
Autoresearch do not each maintain divergent event-name tables.
"""

from __future__ import annotations

from dataclasses import dataclass


NOTIFICATION_POLICIES: frozenset[str] = frozenset({
    "",
    "trace_only",
    "run_manager_first",
    "owner_on_repair_failed",
    "owner_on_human_required",
    "owner_immediate",
})

RECOVERY_POLICIES: frozenset[str] = frozenset({
    "",
    "none",
    "run_manager",
    "autoresearch",
    "run_manager_then_autoresearch",
    "human",
})


@dataclass(frozen=True)
class EventProblemSpec:
    event_type: str
    event_class: str
    problem_class: str = ""
    failure_class: str = ""
    source: str = "workflow_event"
    severity: str = "medium"
    title: str = ""
    owner_route: str = ""
    action_policy: str = ""
    intervention_class: str = ""
    suggested_route: str = ""
    suggested_action_kind: str = ""
    supervisor_attention: str = "none"
    run_manager_semantics: tuple[str, ...] = ()
    autoresearch_eligible: bool = False
    projection_visibility: bool = True
    producer_kind: str = ""
    required_scope_any: tuple[str, ...] = ()
    notification_policy: str = ""
    recovery_policy: str = ""
    dedupe_key_fields: tuple[str, ...] = ()
    human_required_when: tuple[str, ...] = ()

    @property
    def is_expected_negative(self) -> bool:
        return self.event_class == "expected_negative"

    @property
    def is_abnormal(self) -> bool:
        return self.event_class == "abnormal"

    @property
    def is_projection_only(self) -> bool:
        return self.event_class == "projection_only"

    @property
    def effective_notification_policy(self) -> str:
        if self.notification_policy:
            return self.notification_policy
        if self.action_policy == "human_escalate" or self.owner_route in {
            "human",
            "owner_notify",
        }:
            return "owner_immediate"
        if self.owner_route in {"run_manager", "autoresearch"}:
            return "owner_on_repair_failed"
        return "trace_only" if self.is_projection_only else "run_manager_first"

    @property
    def effective_recovery_policy(self) -> str:
        if self.recovery_policy:
            return self.recovery_policy
        if self.action_policy == "human_escalate" or self.owner_route == "human":
            return "human"
        if self.owner_route == "autoresearch" or self.autoresearch_eligible:
            return "run_manager_then_autoresearch"
        if self.owner_route == "run_manager":
            return "run_manager"
        return "none"


def _candidate_quality_expected(event_type: str, title: str = "") -> EventProblemSpec:
    post_terminal_events = {
        "candidate.quality.failed",
        "integration.failed",
        "verify.failed",
        "test.failed",
        "judge.failed",
    }
    return EventProblemSpec(
        event_type=event_type,
        event_class="expected_negative",
        problem_class="candidate_quality",
        failure_class=event_type.replace(".", "_"),
        source="workflow_branch",
        title=title or event_type,
        owner_route="orchestrator_replan",
        action_policy="needs_diagnosis",
        intervention_class="semantic_replan",
        suggested_route="workflow_rework",
        suggested_action_kind="follow_workflow_rework",
        supervisor_attention="on_repeated",
        run_manager_semantics=(
            ("post_terminal_work",) if event_type in post_terminal_events else ()
        ),
        autoresearch_eligible=event_type in {
            "candidate.quality.failed",
            "integration.failed",
            "verify.failed",
            "test.failed",
            "judge.failed",
        },
        producer_kind="workflow_stage",
        required_scope_any=("task_id", "candidate_ref", "pdd_id", "trace_id"),
    )


def _abnormal(
    event_type: str,
    *,
    source: str,
    title: str,
    problem_class: str,
    failure_class: str,
    suggested_action_kind: str,
    severity: str = "high",
    owner_route: str = "run_manager",
    action_policy: str = "needs_diagnosis",
    intervention_class: str = "diagnose",
    notification_policy: str = "owner_on_repair_failed",
    recovery_policy: str = "run_manager_then_autoresearch",
    dedupe_key_fields: tuple[str, ...] = (),
) -> EventProblemSpec:
    return EventProblemSpec(
        event_type=event_type,
        event_class="abnormal",
        problem_class=problem_class,
        failure_class=failure_class,
        source=source,
        severity=severity,
        title=title,
        owner_route=owner_route,
        action_policy=action_policy,
        intervention_class=intervention_class,
        suggested_route="run_manager_recovery",
        suggested_action_kind=suggested_action_kind,
        supervisor_attention="on_single",
        run_manager_semantics=("pending_action",),
        autoresearch_eligible=True,
        producer_kind="runtime",
        required_scope_any=("task_id", "role", "role_instance", "worker_id"),
        notification_policy=notification_policy,
        recovery_policy=recovery_policy,
        dedupe_key_fields=dedupe_key_fields,
    )


def _product_gap_expected(
    event_type: str,
    *,
    failure_class: str,
    title: str,
    source: str,
    suggested_action_kind: str,
    severity: str = "high",
) -> EventProblemSpec:
    return EventProblemSpec(
        event_type=event_type,
        event_class="expected_negative",
        problem_class="product_gap",
        failure_class=failure_class,
        source=source,
        severity=severity,
        title=title,
        owner_route="run_manager",
        action_policy="needs_diagnosis",
        intervention_class="semantic_replan",
        suggested_route="run_manager_recovery",
        suggested_action_kind=suggested_action_kind,
        supervisor_attention="on_repeated",
        run_manager_semantics=("pending_action", "post_terminal_work"),
        autoresearch_eligible=True,
        producer_kind="flow_adapter",
        required_scope_any=(
            "task_id",
            "trace_id",
            "pdd_id",
            "feature_id",
            "target_ref",
            "candidate_ref",
        ),
        notification_policy="owner_on_repair_failed",
        recovery_policy="run_manager_then_autoresearch",
    )


def _artifact_contract_expected(
    event_type: str,
    *,
    failure_class: str,
    title: str,
    suggested_action_kind: str,
) -> EventProblemSpec:
    return EventProblemSpec(
        event_type=event_type,
        event_class="expected_negative",
        problem_class="artifact_contract",
        failure_class=failure_class,
        source="workflow_profile",
        severity="high",
        title=title,
        owner_route="run_manager",
        action_policy="needs_diagnosis",
        intervention_class="semantic_replan",
        suggested_route="run_manager_recovery",
        suggested_action_kind=suggested_action_kind,
        supervisor_attention="on_repeated",
        run_manager_semantics=("pending_action", "post_terminal_work"),
        autoresearch_eligible=True,
        producer_kind="workflow_profile",
        required_scope_any=(
            "task_id",
            "trace_id",
            "pdd_id",
            "feature_id",
            "target_ref",
            "candidate_ref",
        ),
        notification_policy="owner_on_repair_failed",
        recovery_policy="run_manager",
    )


def _kernel_child_result(event_type: str, *, failed: bool) -> EventProblemSpec:
    return EventProblemSpec(
        event_type=event_type,
        event_class="kernel_aggregate_child",
        source="fanout_child",
        severity="medium" if failed else "info",
        title=event_type,
        owner_route="kernel_aggregate",
        action_policy="kernel_consumed",
        intervention_class="aggregate_result",
        suggested_route="kernel_aggregate",
        suggested_action_kind="aggregate_child_result",
        supervisor_attention="none",
        run_manager_semantics=(),
        autoresearch_eligible=False,
        producer_kind="workflow_stage_child",
        required_scope_any=("fanout_id", "stage_id", "task_id"),
    )


def _flow_stage_expected(
    event_type: str,
    *,
    failure_class: str,
    title: str,
    source: str,
    problem_class: str = "product_gap",
    suggested_action_kind: str = "diagnose_flow_stage_failure",
) -> EventProblemSpec:
    return EventProblemSpec(
        event_type=event_type,
        event_class="expected_negative",
        problem_class=problem_class,
        failure_class=failure_class,
        source=source,
        severity="high",
        title=title,
        owner_route="run_manager",
        action_policy="needs_diagnosis",
        intervention_class="semantic_replan",
        suggested_route="run_manager_recovery",
        suggested_action_kind=suggested_action_kind,
        supervisor_attention="on_repeated",
        run_manager_semantics=("pending_action", "post_terminal_work"),
        autoresearch_eligible=True,
        producer_kind="workflow_profile",
        required_scope_any=(
            "task_id",
            "trace_id",
            "pdd_id",
            "feature_id",
            "target_ref",
            "candidate_ref",
            "stage_id",
        ),
    )


EVENT_PROBLEM_SPECS: dict[str, EventProblemSpec] = {
    spec.event_type: spec
    for spec in (
        _candidate_quality_expected("static_gate.failed"),
        _candidate_quality_expected("review.rejected"),
        _candidate_quality_expected("test.failed"),
        _candidate_quality_expected("verify.failed"),
        _candidate_quality_expected("judge.failed"),
        _candidate_quality_expected("integration.failed"),
        _candidate_quality_expected("candidate.quality.failed"),
        _artifact_contract_expected(
            "zaofu.refactor.review.blocked",
            failure_class="refactor_review_blocked",
            title="Refactor review blocked",
            suggested_action_kind="diagnose_refactor_review_blocked",
        ),
        _artifact_contract_expected(
            "zaofu.refactor.plan.blocked",
            failure_class="refactor_plan_blocked",
            title="Refactor plan blocked",
            suggested_action_kind="diagnose_refactor_plan_blocked",
        ),
        _flow_stage_expected(
            "issue.triage.failed",
            failure_class="issue_triage_failed",
            title="Issue triage failed",
            source="issue_flow",
            suggested_action_kind="diagnose_issue_triage_failure",
        ),
        _flow_stage_expected(
            "issue.plan.failed",
            failure_class="issue_plan_failed",
            title="Issue plan failed",
            source="issue_flow",
            problem_class="artifact_contract",
            suggested_action_kind="diagnose_issue_plan_failure",
        ),
        _kernel_child_result("issue.triage.child.completed", failed=False),
        _kernel_child_result("issue.triage.child.failed", failed=True),
        _flow_stage_expected(
            "prd.scan.failed",
            failure_class="prd_scan_failed",
            title="PRD scan failed",
            source="prd_flow",
            suggested_action_kind="diagnose_prd_scan_failure",
        ),
        _kernel_child_result("prd.scan.child.completed", failed=False),
        _kernel_child_result("prd.scan.child.failed", failed=True),
        _flow_stage_expected(
            "prd.plan.failed",
            failure_class="prd_plan_failed",
            title="PRD plan failed",
            source="prd_flow",
            problem_class="artifact_contract",
            suggested_action_kind="diagnose_prd_plan_failure",
        ),
        _flow_stage_expected(
            "prd.blocked",
            failure_class="prd_blocked",
            title="PRD blocked",
            source="prd_flow",
            suggested_action_kind="diagnose_prd_blocked",
        ),
        _kernel_child_result("prd.plan.child.completed", failed=False),
        _kernel_child_result("prd.plan.child.failed", failed=True),
        _kernel_child_result("prd.child.completed", failed=False),
        _kernel_child_result("prd.child.failed", failed=True),
        # research-fanout 固定工作流(zf-research-fanout-trigger)的失败面:
        # 项目配置声明 research 段即产生这两类 actionable 事件,缺 spec 会被
        # strict 冷启动的 missing_consumer_contract 拦启(bizsim r4 实弹)。
        _kernel_child_result("research.child.completed", failed=False),
        _kernel_child_result("research.child.failed", failed=True),
        _flow_stage_expected(
            "research.fanout.failed",
            failure_class="research_fanout_failed",
            title="Research fanout failed",
            source="workflow_runtime",
            suggested_action_kind="diagnose_research_fanout_failure",
        ),
        _kernel_child_result("prd.critic.completed", failed=False),
        _kernel_child_result("prd.critic.failed", failed=True),
        _flow_stage_expected(
            "task_map.amend.failed",
            failure_class="task_map_amend_failed",
            title="Task map amend failed",
            source="workflow_runtime",
            problem_class="artifact_contract",
            suggested_action_kind="diagnose_task_map_amend_failure",
        ),
        _flow_stage_expected(
            "task_map.blocked",
            failure_class="task_map_blocked",
            title="Task map blocked",
            source="workflow_runtime",
            problem_class="artifact_contract",
            suggested_action_kind="diagnose_task_map_blocked",
        ),
        _kernel_child_result("task_map.child.completed", failed=False),
        _kernel_child_result("task_map.child.failed", failed=True),
        _flow_stage_expected(
            "product_delivery.task_map.rejected",
            failure_class="product_delivery_task_map_rejected",
            title="Product delivery task map rejected",
            source="product_delivery",
            problem_class="artifact_contract",
            suggested_action_kind="diagnose_task_map_contract_rejection",
        ),
        _flow_stage_expected(
            "workflow.stage.criteria.failed",
            failure_class="workflow_stage_criteria_failed",
            title="Workflow stage criteria failed",
            source="workflow_stage",
            problem_class="artifact_contract",
            suggested_action_kind="diagnose_stage_criteria_failure",
        ),
        _flow_stage_expected(
            "workflow.stage.output.missing",
            failure_class="workflow_stage_output_missing",
            title="Workflow stage output missing",
            source="workflow_stage",
            problem_class="artifact_contract",
            suggested_action_kind="diagnose_missing_stage_output",
        ),
        _flow_stage_expected(
            "workflow.stage.suspended",
            failure_class="workflow_stage_suspended",
            title="Workflow stage suspended",
            source="workflow_stage",
            problem_class="workflow_progress",
            suggested_action_kind="diagnose_stage_suspension",
        ),
        _kernel_child_result("workflow.child.completed", failed=False),
        _kernel_child_result("workflow.child.failed", failed=True),
        _kernel_child_result("fanout.child.completed", failed=False),
        _kernel_child_result("fanout.child.failed", failed=True),
        _flow_stage_expected(
            "diagnosis.failed",
            failure_class="diagnosis_failed",
            title="Tier-2 diagnosis run failed",
            source="diagnosis_runtime",
            problem_class="workflow_progress",
            suggested_action_kind="diagnose_diagnosis_failure",
        ),
        _flow_stage_expected(
            "fanout.child.workdir_mismatch",
            failure_class="fanout_child_workdir_mismatch",
            title="Reader workdir/target mismatch (dispatch refused)",
            source="fanout_runtime",
            problem_class="artifact_contract",
            suggested_action_kind="diagnose_reader_target_pinning",
        ),
        _kernel_child_result("review.child.completed", failed=False),
        _kernel_child_result("review.child.failed", failed=True),
        _kernel_child_result("impl.child.completed", failed=False),
        _kernel_child_result("impl.child.failed", failed=True),
        _kernel_child_result("verify.child.completed", failed=False),
        _kernel_child_result("verify.child.failed", failed=True),
        _flow_stage_expected(
            "lane.stage.failed",
            failure_class="lane_stage_failed",
            title="Lane stage failed",
            source="lane_pipeline",
            problem_class="workflow_progress",
            suggested_action_kind="diagnose_lane_stage_failure",
        ),
        _flow_stage_expected(
            "dev.failed",
            failure_class="dev_failed",
            title="Development stage failed",
            source="lane_pipeline",
            problem_class="workflow_progress",
            suggested_action_kind="diagnose_impl_failure",
        ),
        _flow_stage_expected(
            "dev.blocked",
            failure_class="dev_blocked",
            title="Development stage blocked",
            source="lane_pipeline",
            problem_class="workflow_progress",
            suggested_action_kind="diagnose_impl_blocker",
        ),
        _flow_stage_expected(
            "gate.failed",
            failure_class="gate_failed",
            title="Gate failed",
            source="workflow_gate",
            problem_class="artifact_contract",
            suggested_action_kind="diagnose_gate_failure",
        ),
        _kernel_child_result("refactor.scan.completed", failed=False),
        _kernel_child_result("refactor.scan.failed", failed=True),
        _kernel_child_result("refactor.plan.child.completed", failed=False),
        _kernel_child_result("refactor.plan.child.failed", failed=True),
        _kernel_child_result("verify.bridge.child.completed", failed=False),
        _kernel_child_result("verify.bridge.child.failed", failed=True),
        _kernel_child_result("module.parity.child.completed", failed=False),
        _kernel_child_result("module.parity.child.failed", failed=True),
        _kernel_child_result("judge.child.completed", failed=False),
        _kernel_child_result("judge.child.failed", failed=True),
        _abnormal(
            "worker.stuck",
            source="runtime_worker",
            title="Worker stuck",
            problem_class="worker_lifecycle",
            failure_class="worker_stuck",
            suggested_action_kind="diagnose_worker_lifecycle",
        ),
        _abnormal(
            "worker.respawn.failed",
            source="runtime_worker",
            title="Worker respawn failed",
            problem_class="worker_lifecycle",
            failure_class="worker_respawn_failed",
            suggested_action_kind="diagnose_worker_lifecycle",
        ),
        _abnormal(
            "worker.recycle.failed",
            source="runtime_worker",
            title="Worker recycle failed",
            problem_class="worker_lifecycle",
            failure_class="worker_recycle_failed",
            suggested_action_kind="diagnose_worker_lifecycle",
        ),
        _abnormal(
            "dispatch.silent_stall",
            source="workflow_runtime",
            title="Dispatch silent stall",
            problem_class="workflow_progress",
            failure_class="dispatch_silent_stall",
            suggested_action_kind="diagnose_worker_noop",
        ),
        _abnormal(
            "owner.visible_message.failed",
            source="owner_delivery",
            title="Owner message delivery failed",
            problem_class="external_gate",
            failure_class="external_gate_delivery_failed",
            suggested_action_kind="diagnose_owner_delivery",
        ),
        _abnormal(
            "owner.visible_message.delivery_failed",
            source="owner_delivery",
            title="Owner message delivery failed",
            problem_class="external_gate",
            failure_class="external_gate_delivery_failed",
            suggested_action_kind="diagnose_owner_delivery",
        ),
        _abnormal(
            "owner.visible_message.expired",
            source="owner_delivery",
            title="Owner message expired",
            problem_class="external_gate",
            failure_class="external_gate_delivery_expired",
            suggested_action_kind="diagnose_owner_delivery",
            severity="medium",
        ),
        _product_gap_expected(
            "flow.discovery.failed",
            failure_class="flow_discovery_failed",
            title="Flow discovery failed",
            source="flow_discovery",
            suggested_action_kind="diagnose_flow_discovery_failure",
        ),
        # dev 合并引入的 discovery 子扇出失败(2026-07-04 基线红清偿):
        # child 结果类必须 kernel_aggregate 先聚合(prod-e2e validate 实弹
        # 纠偏:product_gap 路由会触发 child_result_owner_boundary_violation)
        _kernel_child_result("flow.discovery.child.failed", failed=True),
        _product_gap_expected(
            "goal.rescan.failed",
            failure_class="flow_discovery_failed",
            title="Goal rescan failed",
            source="flow_discovery",
            suggested_action_kind="diagnose_flow_discovery_failure",
        ),
        _product_gap_expected(
            "module.parity.scan.failed",
            failure_class="flow_discovery_failed",
            title="Module parity scan failed",
            source="flow_discovery",
            suggested_action_kind="diagnose_flow_discovery_failure",
        ),
        _product_gap_expected(
            "cangjie.module.parity.scan.failed",
            failure_class="flow_discovery_failed",
            title="Module parity scan failed (legacy Cangjie alias)",
            source="flow_discovery",
            suggested_action_kind="diagnose_flow_discovery_failure",
        ),
        _product_gap_expected(
            "flow.goal.blocked",
            failure_class="flow_goal_blocked",
            title="Flow goal blocked",
            source="flow_goal",
            suggested_action_kind="request_goal_gap_plan",
        ),
        _product_gap_expected(
            "goal.closure.blocked",
            failure_class="flow_goal_blocked",
            title="Goal closure blocked",
            source="flow_goal",
            suggested_action_kind="request_goal_gap_plan",
        ),
        _product_gap_expected(
            "module.parity.blocked",
            failure_class="flow_goal_blocked",
            title="Module parity blocked",
            source="flow_goal",
            suggested_action_kind="request_goal_gap_plan",
        ),
        _product_gap_expected(
            "run.goal.blocked",
            failure_class="flow_goal_blocked",
            title="Run goal blocked",
            source="flow_goal",
            suggested_action_kind="request_goal_gap_plan",
        ),
        # --- E3-4: 存量 36 个 actionable 事件分类清偿(E1 豁免表清零)---
        EventProblemSpec(
            event_type="artifact.manifest.blocked",
            event_class="expected_negative",
            problem_class="artifact_contract",
            failure_class="artifact_manifest_blocked",
            source="workflow_runtime",
            severity="high",
            title="artifact.manifest.blocked",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="manual_review",
            suggested_action_kind="diagnose_artifact_contract",
            supervisor_attention="on_repeated",
            autoresearch_eligible=False,
            producer_kind="kernel",
        ),
        EventProblemSpec(
            event_type="autoresearch.invocation.rejected",
            event_class="expected_negative",
            problem_class="workflow_progress",
            failure_class="autoresearch_invocation_rejected",
            source="workflow_runtime",
            severity="low",
            title="autoresearch.invocation.rejected",
            owner_route="run_manager",
            action_policy="informational",
            suggested_action_kind="informational_governance",
            supervisor_attention="none",
            autoresearch_eligible=False,
            producer_kind="kernel",
        ),
        EventProblemSpec(
            event_type="autoresearch.resident_sidecar.failed",
            event_class="abnormal",
            problem_class="harness",
            failure_class="autoresearch_resident_sidecar_failed",
            source="autoresearch_resident",
            severity="medium",
            title="autoresearch.resident_sidecar.failed",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="repair_harness",
            suggested_action_kind="diagnose_autoresearch_resident_sidecar",
            supervisor_attention="on_repeated",
            autoresearch_eligible=False,
            producer_kind="kernel",
        ),
        EventProblemSpec(
            event_type="approval.rejected_by_policy",
            event_class="expected_negative",
            problem_class="human",
            failure_class="approval_rejected_by_policy",
            source="operator_inbox",
            severity="low",
            title="approval.rejected_by_policy",
            owner_route="run_manager",
            action_policy="informational",
            suggested_action_kind="informational_governance",
            supervisor_attention="none",
            autoresearch_eligible=False,
            producer_kind="kernel",
            notification_policy="trace_only",
            recovery_policy="none",
        ),
        EventProblemSpec(
            event_type="autoscale.scale_down.blocked",
            event_class="expected_negative",
            problem_class="worker_lifecycle",
            failure_class="autoscale_scale_down_blocked",
            source="workflow_runtime",
            severity="low",
            title="autoscale.scale_down.blocked",
            owner_route="run_manager",
            action_policy="informational",
            suggested_action_kind="informational_governance",
            supervisor_attention="none",
            autoresearch_eligible=False,
            producer_kind="kernel",
        ),
        EventProblemSpec(
            event_type="autoscale.scale_up.failed",
            event_class="abnormal",
            problem_class="worker_lifecycle",
            failure_class="autoscale_scale_up_failed",
            source="workflow_runtime",
            severity="medium",
            title="autoscale.scale_up.failed",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="repair_harness",
            suggested_action_kind="diagnose_worker_lifecycle",
            supervisor_attention="on_repeated",
            autoresearch_eligible=False,
            producer_kind="kernel",
        ),
        EventProblemSpec(
            event_type="briefing.hydration.failed",
            event_class="abnormal",
            problem_class="harness",
            failure_class="briefing_hydration_failed",
            source="workflow_runtime",
            severity="high",
            title="briefing.hydration.failed",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="repair_harness",
            suggested_action_kind="diagnose_briefing_hydration",
            supervisor_attention="on_single",
            autoresearch_eligible=True,
            producer_kind="kernel",
        ),
        EventProblemSpec(
            event_type="channel.workflow.rejected",
            event_class="expected_negative",
            problem_class="human",
            failure_class="channel_workflow_rejected",
            source="workflow_runtime",
            severity="low",
            title="channel.workflow.rejected",
            owner_route="run_manager",
            action_policy="informational",
            suggested_action_kind="informational_governance",
            supervisor_attention="none",
            autoresearch_eligible=False,
            producer_kind="kernel",
        ),
        EventProblemSpec(
            event_type="discriminator.failed",
            event_class="expected_negative",
            problem_class="candidate_quality",
            failure_class="discriminator_failed",
            source="workflow_runtime",
            severity="high",
            title="discriminator.failed",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="diagnose",
            suggested_action_kind="follow_workflow_rework",
            supervisor_attention="on_repeated",
            autoresearch_eligible=False,
            producer_kind="kernel",
        ),
        EventProblemSpec(
            event_type="dispatch.blocked",
            event_class="abnormal",
            problem_class="workflow_progress",
            failure_class="dispatch_blocked",
            source="workflow_runtime",
            severity="high",
            title="dispatch.blocked",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="diagnose",
            suggested_action_kind="diagnose_dispatch_blocked",
            supervisor_attention="on_repeated",
            autoresearch_eligible=True,
            producer_kind="kernel",
        ),
        EventProblemSpec(
            event_type="dispatch.briefing_hydration.failed",
            event_class="abnormal",
            problem_class="harness",
            failure_class="dispatch_briefing_hydration_failed",
            source="workflow_runtime",
            severity="high",
            title="dispatch.briefing_hydration.failed",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="repair_harness",
            suggested_action_kind="diagnose_briefing_hydration",
            supervisor_attention="on_single",
            autoresearch_eligible=True,
            producer_kind="kernel",
        ),
        EventProblemSpec(
            event_type="dispatch.terminal.rejected",
            event_class="expected_negative",
            problem_class="contract",
            failure_class="dispatch_terminal_rejected",
            source="workflow_runtime",
            severity="medium",
            title="dispatch.terminal.rejected",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="diagnose",
            suggested_action_kind="diagnose_terminal_rejection",
            supervisor_attention="on_repeated",
            autoresearch_eligible=False,
            producer_kind="kernel",
        ),
        EventProblemSpec(
            event_type="fanout.timed_out",
            event_class="abnormal",
            problem_class="workflow_progress",
            failure_class="fanout_timed_out",
            source="workflow_runtime",
            severity="high",
            title="fanout.timed_out",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="diagnose",
            suggested_action_kind="diagnose_fanout_timeout",
            supervisor_attention="on_single",
            autoresearch_eligible=True,
            producer_kind="kernel",
        ),
        EventProblemSpec(
            event_type="feature.liveness.blocked",
            event_class="expected_negative",
            problem_class="workflow_progress",
            failure_class="feature_liveness_blocked",
            source="workflow_runtime",
            severity="medium",
            title="feature.liveness.blocked",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="diagnose",
            suggested_action_kind="diagnose_feature_liveness",
            supervisor_attention="on_repeated",
            autoresearch_eligible=False,
            producer_kind="kernel",
        ),
        EventProblemSpec(
            event_type="feishu.notification.failed",
            event_class="abnormal",
            problem_class="external_gate",
            failure_class="feishu_notification_failed",
            source="workflow_runtime",
            severity="medium",
            title="feishu.notification.failed",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="repair_harness",
            suggested_action_kind="diagnose_owner_delivery",
            supervisor_attention="on_repeated",
            autoresearch_eligible=False,
            producer_kind="kernel",
        ),
        EventProblemSpec(
            event_type="human.escalate",
            event_class="expected_negative",
            problem_class="human",
            failure_class="human_escalate",
            source="workflow_runtime",
            severity="high",
            title="human.escalate",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="human_decision",
            suggested_action_kind="route_to_operator",
            supervisor_attention="on_single",
            autoresearch_eligible=False,
            producer_kind="kernel",
        ),
        EventProblemSpec(
            event_type="kernel.housekeeping.failed",
            event_class="abnormal",
            problem_class="harness",
            failure_class="kernel_housekeeping_failed",
            source="workflow_runtime",
            severity="high",
            title="kernel.housekeeping.failed",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="repair_harness",
            suggested_action_kind="diagnose_kernel_housekeeping",
            supervisor_attention="on_single",
            autoresearch_eligible=True,
            producer_kind="kernel",
        ),
        EventProblemSpec(
            event_type="orchestrator.tick.failed",
            event_class="abnormal",
            problem_class="harness",
            failure_class="orchestrator_tick_failed",
            source="workflow_runtime",
            severity="high",
            title="orchestrator.tick.failed",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="repair_harness",
            suggested_action_kind="diagnose_watcher_tick",
            supervisor_attention="on_single",
            autoresearch_eligible=True,
            producer_kind="kernel",
        ),
        EventProblemSpec(
            event_type="plan.rejected",
            event_class="expected_negative",
            problem_class="product_gap",
            failure_class="plan_rejected",
            source="workflow_runtime",
            severity="medium",
            title="plan.rejected",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="semantic_replan",
            suggested_action_kind="follow_workflow_rework",
            supervisor_attention="on_repeated",
            autoresearch_eligible=False,
            producer_kind="kernel",
        ),
        EventProblemSpec(
            event_type="scope.snapshot.failed",
            event_class="abnormal",
            problem_class="harness",
            failure_class="scope_snapshot_failed",
            source="workflow_runtime",
            severity="medium",
            title="scope.snapshot.failed",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="repair_harness",
            suggested_action_kind="diagnose_scope_snapshot",
            supervisor_attention="on_repeated",
            autoresearch_eligible=False,
            producer_kind="kernel",
        ),
        EventProblemSpec(
            event_type="ship.blocked",
            event_class="expected_negative",
            problem_class="contract",
            failure_class="ship_blocked",
            source="workflow_runtime",
            severity="high",
            title="ship.blocked",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="manual_review",
            suggested_action_kind="resolve_ship_blockers",
            supervisor_attention="on_single",
            autoresearch_eligible=False,
            producer_kind="kernel",
        ),
        EventProblemSpec(
            event_type="ship.failed",
            event_class="abnormal",
            problem_class="workflow_progress",
            failure_class="ship_failed",
            source="workflow_runtime",
            severity="high",
            title="ship.failed",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="diagnose",
            suggested_action_kind="diagnose_ship_failure",
            supervisor_attention="on_single",
            autoresearch_eligible=True,
            producer_kind="kernel",
        ),
        EventProblemSpec(
            event_type="task.done.blocked",
            event_class="expected_negative",
            problem_class="candidate_quality",
            failure_class="task_done_blocked",
            source="workflow_runtime",
            severity="medium",
            title="task.done.blocked",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="diagnose",
            suggested_action_kind="follow_workflow_rework",
            supervisor_attention="on_repeated",
            autoresearch_eligible=False,
            producer_kind="kernel",
        ),
        EventProblemSpec(
            event_type="task.fanout.rejected",
            event_class="expected_negative",
            problem_class="contract",
            failure_class="task_fanout_rejected",
            source="workflow_runtime",
            severity="medium",
            title="task.fanout.rejected",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="semantic_replan",
            suggested_action_kind="diagnose_fanout_admission",
            supervisor_attention="on_repeated",
            autoresearch_eligible=False,
            producer_kind="kernel",
        ),
        EventProblemSpec(
            event_type="task.ref.rejected",
            event_class="expected_negative",
            problem_class="contract",
            failure_class="task_ref_rejected",
            source="workflow_runtime",
            severity="medium",
            title="task.ref.rejected",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="auto_recover",
            suggested_action_kind="diagnose_task_ref_scope",
            supervisor_attention="on_repeated",
            autoresearch_eligible=False,
            producer_kind="kernel",
        ),
        EventProblemSpec(
            event_type="task.rework.blocked",
            event_class="expected_negative",
            problem_class="workflow_progress",
            failure_class="task_rework_blocked",
            source="workflow_runtime",
            severity="medium",
            title="task.rework.blocked",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="diagnose",
            suggested_action_kind="diagnose_rework_block",
            supervisor_attention="on_repeated",
            autoresearch_eligible=False,
            producer_kind="kernel",
        ),
        EventProblemSpec(
            event_type="task.rework.capped",
            event_class="expected_negative",
            problem_class="workflow_progress",
            failure_class="task_rework_capped",
            source="workflow_runtime",
            severity="high",
            title="task.rework.capped",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="human_decision",
            suggested_action_kind="route_to_operator",
            supervisor_attention="on_single",
            autoresearch_eligible=False,
            producer_kind="kernel",
        ),
        EventProblemSpec(
            event_type="task.rework.triage.blocked",
            event_class="expected_negative",
            problem_class="workflow_progress",
            failure_class="task_rework_triage_blocked",
            source="workflow_runtime",
            severity="medium",
            title="task.rework.triage.blocked",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="diagnose",
            suggested_action_kind="diagnose_rework_block",
            supervisor_attention="on_repeated",
            autoresearch_eligible=False,
            producer_kind="kernel",
        ),
        EventProblemSpec(
            event_type="task.split_quality.blocked",
            event_class="expected_negative",
            problem_class="contract",
            failure_class="task_split_quality_blocked",
            source="workflow_runtime",
            severity="medium",
            title="task.split_quality.blocked",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="semantic_replan",
            suggested_action_kind="follow_workflow_rework",
            supervisor_attention="on_repeated",
            autoresearch_eligible=False,
            producer_kind="kernel",
        ),
        EventProblemSpec(
            event_type="workdir.dependency_apply.failed",
            event_class="abnormal",
            problem_class="harness",
            failure_class="workdir_dependency_apply_failed",
            source="workflow_runtime",
            severity="medium",
            title="workdir.dependency_apply.failed",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="repair_project",
            suggested_action_kind="diagnose_workdir_provision",
            supervisor_attention="on_repeated",
            autoresearch_eligible=False,
            producer_kind="kernel",
        ),
        EventProblemSpec(
            event_type="worker.context.compact.failed",
            event_class="abnormal",
            problem_class="harness",
            failure_class="worker_context_compact_failed",
            source="workflow_runtime",
            severity="medium",
            title="worker.context.compact.failed",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="repair_harness",
            suggested_action_kind="diagnose_worker_context",
            supervisor_attention="on_repeated",
            autoresearch_eligible=False,
            producer_kind="kernel",
        ),
        EventProblemSpec(
            event_type="worker.pane.dead_observed",
            event_class="abnormal",
            problem_class="worker_lifecycle",
            failure_class="worker_pane_dead_observed",
            source="workflow_runtime",
            severity="high",
            title="worker.pane.dead_observed",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="auto_recover",
            suggested_action_kind="diagnose_worker_lifecycle",
            supervisor_attention="on_single",
            autoresearch_eligible=True,
            producer_kind="kernel",
        ),
        EventProblemSpec(
            event_type="worker.runner.failed",
            event_class="abnormal",
            problem_class="harness",
            failure_class="worker_runner_failed",
            source="workflow_runtime",
            severity="high",
            title="worker.runner.failed",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="auto_recover",
            suggested_action_kind="diagnose_worker_lifecycle",
            supervisor_attention="on_single",
            autoresearch_eligible=True,
            producer_kind="kernel",
        ),
        EventProblemSpec(
            event_type="worker.runtime_write.rejected",
            event_class="expected_negative",
            problem_class="contract",
            failure_class="worker_runtime_write_rejected",
            source="workflow_runtime",
            severity="medium",
            title="worker.runtime_write.rejected",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="manual_review",
            suggested_action_kind="diagnose_runtime_write_guard",
            supervisor_attention="on_repeated",
            autoresearch_eligible=False,
            producer_kind="kernel",
        ),
        EventProblemSpec(
            event_type="worker.stuck.recovered",
            event_class="projection_only",
            problem_class="workflow_progress",
            failure_class="worker_stuck_recovered",
            source="workflow_runtime",
            severity="low",
            title="worker.stuck.recovered",
            owner_route="run_manager",
            action_policy="informational",
            suggested_action_kind="informational_recovery",
            supervisor_attention="none",
            autoresearch_eligible=False,
            producer_kind="kernel",
        ),
        EventProblemSpec(
            event_type="worker.stuck.recovery_failed",
            event_class="abnormal",
            problem_class="workflow_progress",
            failure_class="worker_stuck_recovery_failed",
            source="workflow_runtime",
            severity="high",
            title="worker.stuck.recovery_failed",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="human_decision",
            suggested_action_kind="diagnose_worker_lifecycle",
            supervisor_attention="on_single",
            autoresearch_eligible=True,
            producer_kind="kernel",
        ),
        EventProblemSpec(
            event_type="workflow.invoke.rejected",
            event_class="expected_negative",
            problem_class="contract",
            failure_class="workflow_invoke_rejected",
            source="workflow_runtime",
            severity="low",
            title="workflow.invoke.rejected",
            owner_route="run_manager",
            action_policy="informational",
            suggested_action_kind="informational_governance",
            supervisor_attention="none",
            autoresearch_eligible=False,
            producer_kind="kernel",
        ),
        EventProblemSpec(
            event_type="workflow.submit.rejected",
            event_class="expected_negative",
            problem_class="contract",
            failure_class="workflow_submit_rejected",
            source="workflow_runtime",
            severity="low",
            title="workflow.submit.rejected",
            owner_route="run_manager",
            action_policy="informational",
            suggested_action_kind="informational_governance",
            supervisor_attention="none",
            autoresearch_eligible=False,
            producer_kind="kernel",
        ),
        # --- 裁决 B(2026-07-04):environment problem_class 正式启用,
        # env 层故障从此有事件身份,不再伪装成调度故障(D12/avbs-r5)---
        EventProblemSpec(
            event_type="env.preflight.failed",
            event_class="abnormal",
            problem_class="environment",
            failure_class="env_preflight_failed",
            source="env_preflight",
            severity="high",
            title="Environment preflight check failed",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="operator_resume",
            suggested_action_kind="repair_environment_before_dispatch",
            supervisor_attention="on_single",
            producer_kind="kernel",
        ),
        EventProblemSpec(
            event_type="cost.usage.blackout",
            event_class="abnormal",
            problem_class="harness",
            failure_class="cost_usage_blackout",
            source="workflow_runtime",
            severity="high",
            title="Cost usage collection stopped while dispatch active",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="diagnose",
            suggested_action_kind="diagnose_cost_collection",
            supervisor_attention="on_single",
            producer_kind="kernel",
            notification_policy="owner_on_repair_failed",
            recovery_policy="run_manager_then_autoresearch",
            dedupe_key_fields=("scope", "role", "task_id"),
        ),
        EventProblemSpec(
            event_type="cost.budget.exceeded",
            event_class="abnormal",
            problem_class="runtime_liveness",
            failure_class="cost_budget_exceeded",
            source="kernel_budget",
            severity="high",
            title="Cost budget exceeded",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="diagnose",
            suggested_route="run_manager_recovery",
            suggested_action_kind="diagnose_budget_exceeded",
            supervisor_attention="on_single",
            run_manager_semantics=("pending_action",),
            autoresearch_eligible=False,
            producer_kind="kernel",
            required_scope_any=("scope", "role", "task_id", "trace_id"),
            notification_policy="owner_on_human_required",
            recovery_policy="run_manager",
            dedupe_key_fields=("scope", "role", "budget_usd"),
            human_required_when=(
                "budget_level_changed",
                "owner_budget_decision_needed",
                "run_manager_no_progress",
            ),
        ),
        # --- E5(131-P2):attempt 合同决策事件 ---
        # 族内映射(131-P2-1 裁决 A 收编口径):started/succeeded/failed
        # 由 task.dispatched / dev.build.done / dev.failed 承载(P2-2 兼容
        # 映射,attempt_ledger 派生);heartbeat 由 worker.heartbeat 承载。
        # 显式发射的只有决策点新增信息:retry_scheduled(ordinal/cap/
        # lease_token)与 deadlettered(non-retryable 短路)。
        EventProblemSpec(
            event_type="task.attempt.started",
            event_class="projection_only",
            problem_class="workflow_progress",
            failure_class="task_attempt_started",
            source="kernel_dispatch",
            severity="low",
            title="Task attempt started",
            owner_route="run_manager",
            action_policy="informational",
            supervisor_attention="none",
            producer_kind="kernel",
            required_scope_any=("task_id",),
        ),
        EventProblemSpec(
            event_type="task.attempt.heartbeat",
            event_class="projection_only",
            problem_class="workflow_progress",
            failure_class="task_attempt_heartbeat",
            source="kernel_dispatch",
            severity="low",
            title="Task attempt heartbeat",
            owner_route="run_manager",
            action_policy="informational",
            supervisor_attention="none",
            producer_kind="kernel",
            required_scope_any=("task_id",),
        ),
        EventProblemSpec(
            event_type="task.attempt.succeeded",
            event_class="projection_only",
            problem_class="workflow_progress",
            failure_class="task_attempt_succeeded",
            source="kernel_dispatch",
            severity="low",
            title="Task attempt succeeded",
            owner_route="run_manager",
            action_policy="informational",
            supervisor_attention="none",
            producer_kind="kernel",
            required_scope_any=("task_id",),
        ),
        EventProblemSpec(
            event_type="task.attempt.failed",
            event_class="expected_negative",
            problem_class="workflow_progress",
            failure_class="task_attempt_failed",
            source="kernel_dispatch",
            severity="medium",
            title="Task attempt failed",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="diagnose",
            suggested_action_kind="diagnose_task_attempt_failure",
            supervisor_attention="on_repeated",
            run_manager_semantics=("pending_action",),
            autoresearch_eligible=True,
            producer_kind="kernel",
            required_scope_any=("task_id",),
        ),
        EventProblemSpec(
            event_type="task.attempt.retry_scheduled",
            event_class="projection_only",
            problem_class="workflow_progress",
            failure_class="task_attempt_retry_scheduled",
            source="kernel_dispatch",
            severity="low",
            title="Rework attempt scheduled (counted ordinal + cap + lease token)",
            owner_route="run_manager",
            action_policy="informational",
            supervisor_attention="none",
            producer_kind="kernel",
            required_scope_any=("task_id",),
        ),
        EventProblemSpec(
            event_type="task.attempt.deadlettered",
            event_class="expected_negative",
            problem_class="environment",
            failure_class="task_attempt_deadlettered",
            source="kernel_dispatch",
            severity="high",
            title="Non-retryable failure deadlettered (no retry budget burned)",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="operator_resume",
            suggested_action_kind="repair_environment_then_operator_resume",
            supervisor_attention="on_single",
            producer_kind="kernel",
            required_scope_any=("task_id",),
        ),
        EventProblemSpec(
            event_type="impl.evidence.missing",
            event_class="projection_only",
            problem_class="artifact_contract",
            failure_class="impl_evidence_missing",
            source="kernel_gate",
            severity="medium",
            title="Impl completion carried no evidence refs (strict profile)",
            owner_route="run_manager",
            action_policy="informational",
            intervention_class="none",
            suggested_action_kind="observe_only",
            supervisor_attention="on_repeated",
            producer_kind="kernel",
            required_scope_any=("task_id",),
        ),
        EventProblemSpec(
            event_type="workflow.resume.gate_unroutable",
            event_class="abnormal",
            problem_class="workflow_progress",
            failure_class="gate_dispatch_unroutable",
            source="workflow_resume",
            severity="high",
            title="Accepted completion has no executable gate dispatch route",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="diagnose",
            suggested_route="run_manager_recovery",
            suggested_action_kind="diagnose_attention",
            supervisor_attention="on_repeated",
            producer_kind="kernel",
            required_scope_any=("task_id",),
        ),
        EventProblemSpec(
            event_type="cost.blocked_role_burn",
            event_class="abnormal",
            problem_class="harness",
            failure_class="blocked_role_token_burn",
            source="kernel_tick",
            severity="high",
            title="Blocked role keeps consuming tokens",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="diagnose",
            suggested_route="run_manager_recovery",
            suggested_action_kind="diagnose_attention",
            supervisor_attention="on_single",
            producer_kind="kernel",
            required_scope_any=("trace_id", "task_id", "pdd_id"),
        ),
        EventProblemSpec(
            event_type="dev.completion.claims_unverified",
            event_class="abnormal",
            problem_class="candidate_quality",
            failure_class="completion_claims_unverified",
            source="kernel_admission",
            severity="high",
            title="Completion event claims artifacts/head that do not exist",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="diagnose",
            suggested_route="workflow_rework",
            suggested_action_kind="diagnose_attention",
            supervisor_attention="on_single",
            producer_kind="kernel",
            required_scope_any=("task_id",),
        ),
        EventProblemSpec(
            event_type="run.manager.action.no_progress_break",
            event_class="abnormal",
            problem_class="workflow_progress",
            failure_class="rm_outcome_no_progress",
            source="run_manager",
            severity="high",
            title="RM outcome circuit breaker: repeated action with zero task progress",
            owner_route="run_manager",
            action_policy="human_escalate",
            intervention_class="human_decision",
            suggested_route="owner_notify",
            suggested_action_kind="diagnose_attention",
            supervisor_attention="on_single",
            producer_kind="kernel",
            required_scope_any=("task_id",),
            notification_policy="owner_immediate",
            recovery_policy="human",
        ),
        # --- avbs-r4/r5 F 批新事件注册(131-P1 closure 首批,E1)---
        EventProblemSpec(
            event_type="fanout.duplicate_suppressed",
            event_class="projection_only",
            problem_class="workflow_progress",
            failure_class="fanout_duplicate_suppressed",
            source="kernel_admission",
            severity="low",
            title="Equivalent fanout re-emit suppressed",
            owner_route="run_manager",
            action_policy="informational",
            intervention_class="none",
            suggested_action_kind="observe_only",
            supervisor_attention="on_repeated",
            producer_kind="kernel",
            required_scope_any=("pdd_id", "trace_id", "stage_id"),
        ),
        EventProblemSpec(
            event_type="rework.routing.scope_mismatch",
            event_class="abnormal",
            problem_class="contract",
            failure_class="rework_routing_scope_mismatch",
            source="kernel_dispatch",
            severity="high",
            title="Rework routed to a task that cannot touch the finding paths",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="semantic_replan",
            suggested_route="workflow_rework",
            suggested_action_kind="reroute_rework_to_finding_owner",
            supervisor_attention="on_single",
            autoresearch_eligible=True,
            producer_kind="kernel",
            required_scope_any=("task_id", "trace_id"),
        ),
        EventProblemSpec(
            event_type="runtime.watcher.lag_warning",
            event_class="abnormal",
            problem_class="harness",
            failure_class="watcher_backlog",
            source="workflow_runtime",
            severity="high",
            title="Event watcher backlog above threshold",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="diagnose",
            suggested_action_kind="flush_restart_at_safe_window",
            supervisor_attention="on_single",
            producer_kind="kernel",
            required_scope_any=(),
        ),
        EventProblemSpec(
            event_type="verification.waived",
            event_class="projection_only",
            problem_class="human",
            failure_class="verification_waived",
            source="operator_decision",
            severity="low",
            title="Operator waived a verification command/finding",
            owner_route="run_manager",
            action_policy="informational",
            supervisor_attention="none",
            producer_kind="operator",
            required_scope_any=("task_id",),
        ),
        EventProblemSpec(
            event_type="verification.waiver.revoked",
            event_class="projection_only",
            problem_class="human",
            failure_class="verification_waiver_revoked",
            source="operator_decision",
            severity="low",
            title="Operator revoked a verification waiver",
            owner_route="run_manager",
            action_policy="informational",
            supervisor_attention="none",
            producer_kind="operator",
            required_scope_any=("task_id",),
        ),
        EventProblemSpec(
            event_type="candidate.rework.quarantined",
            event_class="expected_negative",
            problem_class="workflow_progress",
            failure_class="candidate_rework_quarantined",
            source="workflow_runtime",
            severity="medium",
            title="Rework re-arm suppressed after escalation (R22 quarantine)",
            owner_route="run_manager",
            action_policy="needs_diagnosis",
            intervention_class="semantic_replan",
            suggested_action_kind="operator_authorized_resume_or_clear",
            supervisor_attention="on_repeated",
            producer_kind="kernel",
            required_scope_any=("pdd_id", "trace_id"),
        ),
    )
}


EXPECTED_NEGATIVE_EVENT_TYPES: frozenset[str] = frozenset(
    event_type
    for event_type, spec in EVENT_PROBLEM_SPECS.items()
    if spec.event_class == "expected_negative"
)

ABNORMAL_EVENT_TYPES: frozenset[str] = frozenset(
    event_type
    for event_type, spec in EVENT_PROBLEM_SPECS.items()
    if spec.event_class == "abnormal"
)

AUTORESEARCH_ELIGIBLE_FAILURE_CLASSES: tuple[str, ...] = tuple(sorted({
    spec.failure_class
    for spec in EVENT_PROBLEM_SPECS.values()
    if spec.autoresearch_eligible and spec.failure_class
}))

RUN_MANAGER_POST_TERMINAL_EVENT_TYPES: frozenset[str] = frozenset(
    event_type
    for event_type, spec in EVENT_PROBLEM_SPECS.items()
    if "post_terminal_work" in spec.run_manager_semantics
)

RUN_MANAGER_PENDING_EVENT_TYPES: frozenset[str] = frozenset(
    event_type
    for event_type, spec in EVENT_PROBLEM_SPECS.items()
    if "pending_action" in spec.run_manager_semantics
)


def spec_for_event(event_type: str) -> EventProblemSpec | None:
    return EVENT_PROBLEM_SPECS.get(str(event_type or "").strip())


def expected_negative_event_types() -> frozenset[str]:
    return EXPECTED_NEGATIVE_EVENT_TYPES


def abnormal_event_specs() -> dict[str, EventProblemSpec]:
    return {
        event_type: spec
        for event_type, spec in EVENT_PROBLEM_SPECS.items()
        if spec.event_class == "abnormal"
    }


def autoresearch_eligible_failure_classes() -> tuple[str, ...]:
    return AUTORESEARCH_ELIGIBLE_FAILURE_CLASSES


def event_consumer_contract_gaps(event_types: set[str]) -> list[str]:
    """Return event types that look actionable but lack a registry consumer.

    This intentionally focuses on workflow/problem events rather than all
    telemetry. A role may publish a project-specific info event without a
    runtime consumer; failure/block/reject events are the dangerous class.
    """

    gaps: list[str] = []
    for event_type in sorted(str(item or "").strip() for item in event_types):
        if not event_type:
            continue
        if not looks_actionable_event(event_type):
            continue
        spec = spec_for_event(event_type)
        if spec is None or (
            spec.is_projection_only
            and spec.supervisor_attention == "none"
            and not spec.autoresearch_eligible
            and "pending_action" not in spec.run_manager_semantics
        ):
            gaps.append(event_type)
    return gaps


def looks_actionable_event(event_type: str) -> bool:
    return any(
        event_type.endswith(suffix)
        for suffix in (
            ".failed",
            ".blocked",
            ".rejected",
            ".suspended",
            ".missing",
        )
    )


def actionable_event_types(event_types: set[str]) -> set[str]:
    return {
        event_type
        for event_type in (str(item or "").strip() for item in event_types)
        if event_type and looks_actionable_event(event_type)
    }


__all__ = [
    "ABNORMAL_EVENT_TYPES",
    "AUTORESEARCH_ELIGIBLE_FAILURE_CLASSES",
    "EVENT_PROBLEM_SPECS",
    "EXPECTED_NEGATIVE_EVENT_TYPES",
    "NOTIFICATION_POLICIES",
    "RECOVERY_POLICIES",
    "RUN_MANAGER_PENDING_EVENT_TYPES",
    "RUN_MANAGER_POST_TERMINAL_EVENT_TYPES",
    "EventProblemSpec",
    "abnormal_event_specs",
    "actionable_event_types",
    "autoresearch_eligible_failure_classes",
    "event_consumer_contract_gaps",
    "expected_negative_event_types",
    "looks_actionable_event",
    "spec_for_event",
]
