"""LH-6.T6: read results.tsv → emit longhorizon-health-v<N>.md.

Section template (order matters — readers skim top-down):
  1. Executive summary (best VCR, baseline, # iterations)
  2. Per-metric ascii trend sparkline
  3. Guard violation counts
  4. Top N keep experiments (best delta)
  5. Top N discards + inferred reason
  6. Recommended next config (best iteration's knobs)
"""

from __future__ import annotations

import csv
from collections import Counter
from pathlib import Path


_SPARK = "▁▂▃▄▅▆▇█"


def _sparkline(values: list[float]) -> str:
    if not values:
        return "(none)"
    if all(v == values[0] for v in values):
        return _SPARK[0] * len(values)
    mn, mx = min(values), max(values)
    span = mx - mn or 1
    return "".join(
        _SPARK[min(len(_SPARK) - 1,
                     int((v - mn) / span * (len(_SPARK) - 1)))]
        for v in values
    )


def render(results_path: Path) -> str:
    if not results_path.exists():
        return "# Long-Horizon Health Report\n\n_(no results yet)_\n"

    with results_path.open(newline="") as f:
        rows = list(csv.DictReader(f, delimiter="\t"))
    if not rows:
        return "# Long-Horizon Health Report\n\n_(empty results.tsv)_\n"

    vcrs = [float(r["vcr"]) for r in rows]
    mttss = [float(r["mtts"]) for r in rows]
    costs = [float(r["cost_per_task"]) for r in rows]
    reworks = [float(r["rework_ratio"]) for r in rows]

    best_row = max(rows, key=lambda r: float(r["vcr"]))
    baseline_row = next(
        (r for r in rows if r["note"].startswith("baseline")), rows[0],
    )

    guard_counter = Counter(r["guard_status"] for r in rows)
    status_counter = Counter(r["note"].split(":", 1)[0] for r in rows)

    keeps = [r for r in rows if r["note"].startswith("keep")]
    discards = [r for r in rows if r["note"].startswith("discard")]
    keeps.sort(key=lambda r: float(r["vcr"]), reverse=True)

    lines: list[str] = []
    lines.append("# Long-Horizon Health Report")
    lines.append("")
    lines.append("## Executive summary")
    lines.append("")
    lines.append(f"- Iterations: **{len(rows)}**")
    lines.append(
        f"- Baseline VCR: `{baseline_row['vcr']}`  · "
        f"Best VCR: `{best_row['vcr']}` (iteration "
        f"`{best_row['iteration']}`)"
    )
    lines.append(
        f"- Best config note: `{best_row['note']}`"
    )
    lines.append("")

    lines.append("## Metric trends")
    lines.append("")
    lines.append(f"- VCR            {_sparkline(vcrs)}  (last {vcrs[-1]:.3f})")
    lines.append(f"- MTTS           {_sparkline(mttss)}  (last {mttss[-1]:.2f})")
    lines.append(f"- Cost/Task      {_sparkline(costs)}  (last ${costs[-1]:.4f})")
    lines.append(f"- ReworkRatio    {_sparkline(reworks)}  (last {reworks[-1]:.2f})")
    lines.append("")

    lines.append("## Guard violations")
    lines.append("")
    for status, count in guard_counter.most_common():
        lines.append(f"- `{status}`: {count}")
    lines.append("")

    lines.append(f"## Top {min(5, len(keeps))} keep experiments")
    lines.append("")
    for r in keeps[:5]:
        lines.append(
            f"- iter {r['iteration']} VCR={r['vcr']}  {r['note']}"
        )
    if not keeps:
        lines.append("_(no keep iterations yet)_")
    lines.append("")

    lines.append(f"## Top {min(5, len(discards))} discards")
    lines.append("")
    for r in discards[:5]:
        lines.append(
            f"- iter {r['iteration']} VCR={r['vcr']}  {r['note']}"
        )
    if not discards:
        lines.append("_(no discards yet)_")
    lines.append("")

    lines.append("## Recommended next config")
    lines.append("")
    lines.append(
        f"- Use `{best_row['note']}` (VCR={best_row['vcr']}) as a seed"
    )
    lines.append("")
    lines.append("_(report auto-generated by tests/longhorizon/report.py)_")
    return "\n".join(lines) + "\n"


def write_report(results_path: Path, out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render(results_path), encoding="utf-8")
