"""TR-AGENTS-MD-MANAGED-001 (doc 42 §2.5 A) — AGENTS.md managed block.

Outside the ``<!-- ZF:START -->`` / ``<!-- ZF:END -->`` markers stays user-
editable; inside is regenerated by ``zf update agents-md --write`` from
``render_canonical_block()``. The managed-block pattern keeps generated
and hand-edited regions in one file (doc 42 §2.5 A).

This module is intentionally small (no I/O — caller passes file content as
``str``) so it is trivial to test and so the CLI / future ``zf update``
subcommands can compose it without circular imports.

Design rules:
- Markers MUST appear on their own line (no inline). Inline markers in
  surrounding prose would not be recognised, by design.
- Only one pair of markers is allowed per file. Multiple START or END
  markers raise ``AgentsMdError`` — operator must fix the file.
- ``replace_managed_block`` preserves all content outside the markers
  byte-for-byte. Idempotent: re-running with the same ``new_inside``
  produces an identical file.
"""

from __future__ import annotations

import re

ZF_MARKER_START = "<!-- ZF:START -->"
ZF_MARKER_END = "<!-- ZF:END -->"


class AgentsMdError(Exception):
    """Raised when AGENTS.md managed-block markers are malformed."""


def _find_marker_positions(text: str) -> tuple[int, int] | None:
    """Return (start_line_idx, end_line_idx) — 0-based line indices of the
    START and END marker lines. Returns ``None`` if no markers.

    Raises:
        AgentsMdError: malformed marker arrangement (multiple START,
            missing END when START present, END before START).
    """
    lines = text.splitlines()
    starts = [i for i, ln in enumerate(lines) if ln.strip() == ZF_MARKER_START]
    ends = [i for i, ln in enumerate(lines) if ln.strip() == ZF_MARKER_END]

    if not starts and not ends:
        return None
    if len(starts) > 1:
        raise AgentsMdError(
            f"AGENTS.md has {len(starts)} <!-- ZF:START --> markers; "
            f"only one pair allowed"
        )
    if len(ends) > 1:
        raise AgentsMdError(
            f"AGENTS.md has {len(ends)} <!-- ZF:END --> markers; "
            f"only one pair allowed"
        )
    if not starts:
        raise AgentsMdError(
            "AGENTS.md has <!-- ZF:END --> without matching <!-- ZF:START -->"
        )
    if not ends:
        raise AgentsMdError(
            "AGENTS.md has <!-- ZF:START --> without matching <!-- ZF:END -->"
        )
    if ends[0] <= starts[0]:
        raise AgentsMdError(
            "AGENTS.md has <!-- ZF:END --> appearing before <!-- ZF:START -->"
        )
    return (starts[0], ends[0])


def extract_managed_block(text: str) -> str | None:
    """Return the text strictly between the START / END markers.

    Returns ``None`` if the markers are not present (clean state — caller
    can decide whether to create them via ``replace_managed_block``).
    Raises ``AgentsMdError`` on malformed marker arrangement.

    The returned text excludes the marker lines themselves and has no
    trailing newline (so equality tests are clean).
    """
    positions = _find_marker_positions(text)
    if positions is None:
        return None
    start_idx, end_idx = positions
    lines = text.splitlines()
    inside_lines = lines[start_idx + 1:end_idx]
    return "\n".join(inside_lines)


def replace_managed_block(text: str, new_inside: str) -> str:
    """Return text with the managed block content replaced by ``new_inside``.

    Behaviour:
    - If markers are present: replace only the content between them.
      All bytes outside (above START, below END) are preserved exactly.
    - If markers are absent: append a fresh block at end of file
      (separated from existing content by one blank line if not already).
    - Idempotent: ``replace_managed_block(replace_managed_block(t, x), x) ==
      replace_managed_block(t, x)``.

    ``new_inside`` should NOT include the marker lines (this function
    wraps them). Leading / trailing newlines in ``new_inside`` are
    normalised to exactly one blank line on each side of the marker
    content for a consistent look.
    """
    normalised = new_inside.strip("\n")
    positions = _find_marker_positions(text)
    if positions is None:
        # No markers — append a fresh block.
        prefix = text.rstrip("\n")
        sep = "\n\n" if prefix else ""
        return (
            f"{prefix}{sep}"
            f"{ZF_MARKER_START}\n"
            f"{normalised}\n"
            f"{ZF_MARKER_END}\n"
        )
    # Markers present — splice replacement preserving line endings.
    start_idx, end_idx = positions
    lines = text.splitlines(keepends=True)
    # We rebuild as: lines[:start_idx+1] (incl START line) + replacement +
    # lines[end_idx:] (starts at END line)
    before = "".join(lines[:start_idx + 1])
    after = "".join(lines[end_idx:])
    # Ensure START line and END line each terminate with a newline so the
    # inside content is on its own lines. splitlines(keepends=True) gives
    # back the original newline (or none if final line lacked one).
    if not before.endswith("\n"):
        before += "\n"
    return f"{before}{normalised}\n{after}"


# ---------------------------------------------------------------------------
# Canonical block content
# ---------------------------------------------------------------------------


def render_canonical_block(*, config=None) -> str:
    """Return the canonical ZaoFu worker-protocol block content.

    Canonical generated content — hand-maintained against stable symbols:
    - ``injection.generate_task_briefing`` (active task pin)
    - ``injection._render_recursion_guard`` (recursion guard)
    - ``injection._render_worker_heartbeat_instructions`` (heartbeat)
    - ``inline_overrides.scan_inline_overrides`` (override audit)
    - docs/design/13-interaction-protocol.md
    - docs/design/142-layered-runtime-authority-and-orchestration-modes.md

    ``config`` parameter reserved for future per-config customisation
    (e.g. if ``cost.budget_usd`` is set, the block may add a budget
    reminder). Currently unused — kept in signature for forward compat.
    """
    _ = config  # reserved
    return """## Worker Protocol (managed by ZaoFu — do not edit between markers)

This block is regenerated by `zf update agents-md --write`. Edits inside the
ZF markers will be overwritten. Edit outside the markers freely.

### Scope guard

This protocol applies only when the current ZaoFu dispatch briefing begins
with `Active task: <task_id>`. In an ordinary interactive development, review,
or operator session without that marker, do not emit task/workflow events or
heartbeats merely because this block is present.

### Active task pin

The first line of every worker briefing is `Active task: <task_id>`. Every
event you emit MUST reference this id; do not invent a different id even if
the user message contains one. Recovery / operator-side scripts grep this
line to confirm a worker is actually working on the expected task. Missing
or mismatched id is treated as fail-closed.

Source: `src/zf/runtime/injection.py::generate_task_briefing`;
contract test: `tests/test_runtime_injection.py`.

### Event emission channel

Workers report state-change intent through
`zf emit <event-type> --task <task_id>`. Do NOT write directly to
`kanban.json` / `feature_list.json` / `progress.md` / `memory/`; use sanctioned
`zf` CLI commands or kernel actions so runtime state remains coordinated.

### Self-declared completion prohibition

Workers MUST NOT emit terminal completion events (`*.passed`, `*.approved`,
`task.done`) on their own role's behalf without supporting gate evidence.
The kernel discriminator (`ContractD` / `FunctionalD` / others) verifies the
evidence and may reject self-declarations; rejections route to bounded
rework via `rework_routing` (see `zf.yaml`).

### Sub-agent recursion guard

If your briefing contains the `## Recursion Guard (强制)` section, you are
running as a sub-task worker. Within that scope:

- Do NOT dispatch additional same-role sub-tasks.
- Execute the parent briefing's instructions only.
- Do NOT modify `tasks/` / `feature_list.json` / `kanban.json` unless the
  parent briefing explicitly requests it.

Source: `src/zf/runtime/injection.py::_render_recursion_guard`;
contract test: `tests/test_runtime_injection.py`.

### Inline-override audit

User messages containing literal keywords like `"skip critic"` / `"skip test"`
/ `"跳过 critic"` / `"跳过 test"` trigger an audit event and may skip a
stage. Workers MUST NOT synthesize these keywords on the user's behalf,
and MUST emit the corresponding audit event when honoring an override.

Source: `src/zf/runtime/inline_overrides.py::scan_inline_overrides`;
contract tests: `tests/test_inline_override_scanner.py` and orchestration tests.

### Heartbeat

Only while an active task marker is present and the task is `in_progress`,
follow the exact `worker.heartbeat` command and cadence rendered in that task's
briefing. Never invent or reuse a task id, and never emit a heartbeat from an
ordinary repo-maintenance session.
"""


__all__ = [
    "ZF_MARKER_START",
    "ZF_MARKER_END",
    "AgentsMdError",
    "extract_managed_block",
    "replace_managed_block",
    "render_canonical_block",
]
