"""ZF-PWF-ATTEST-001 §3.2-§3.5 — artifact attestation (doc 41 §4.3, I62 candidate).

Computes + writes SHA-256 attestations for the 6 artifact classes
zaofu treats as frozen handoff inputs:

1. task contract freeze
2. State Packet
3. dispatch context manifest
4. role instructions briefing
5. required skills manifest (skills.lock)
6. research artifact index

Attestation file shape (one per artifact)::

    .zf/attestations/<safe-path>.attest.json
    {
      "schema_version": "1.0",
      "artifact_path": "<source>",
      "kind": "<one-of-6>",
      "sha256": "<hex>",
      "source_events": ["evt-..."],
      "task_id": "TASK-...",
      "dispatch_id": "disp-...",
      "attested_at": "<iso>"
    }

Discipline:
- Attestation is generated by the kernel after a stable artifact is
  written. Workers cannot mutate ``.zf/attestations/*``.
- Recovery / dispatch path can call :func:`verify_attestation` to
  detect tampering; on hash mismatch the caller fails closed.
- Schema-versioned ("1.0"). Future fields go in 1.x.
"""

from __future__ import annotations

import json
import re
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from zf.core.security.hash import sha256_file, sha256_json, sha256_text
from zf.core.state.atomic_io import atomic_write_text


ATTESTATION_SCHEMA_VERSION = "1.0"

ATTESTATION_KIND_TASK_CONTRACT = "task_contract"
ATTESTATION_KIND_STATE_PACKET = "state_packet"
ATTESTATION_KIND_CONTEXT_MANIFEST = "context_manifest"
ATTESTATION_KIND_ROLE_BRIEFING = "role_briefing"
ATTESTATION_KIND_SKILLS_MANIFEST = "skills_manifest"
ATTESTATION_KIND_RESEARCH_INDEX = "research_index"

KNOWN_ATTESTATION_KINDS: frozenset[str] = frozenset({
    ATTESTATION_KIND_TASK_CONTRACT,
    ATTESTATION_KIND_STATE_PACKET,
    ATTESTATION_KIND_CONTEXT_MANIFEST,
    ATTESTATION_KIND_ROLE_BRIEFING,
    ATTESTATION_KIND_SKILLS_MANIFEST,
    ATTESTATION_KIND_RESEARCH_INDEX,
})


@dataclass(frozen=True)
class Attestation:
    """Immutable record of one artifact's frozen state."""

    artifact_path: str
    kind: str
    sha256: str
    schema_version: str = ATTESTATION_SCHEMA_VERSION
    source_events: tuple[str, ...] = ()
    task_id: str = ""
    dispatch_id: str = ""
    attested_at: str = ""

    def __post_init__(self) -> None:
        if self.kind not in KNOWN_ATTESTATION_KINDS:
            raise ValueError(
                f"Attestation.kind {self.kind!r} not in "
                f"{sorted(KNOWN_ATTESTATION_KINDS)}"
            )
        if not re.fullmatch(r"[0-9a-f]{64}", self.sha256):
            raise ValueError(
                f"Attestation.sha256 must be 64-hex; got {self.sha256!r}"
            )


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _safe_path_part(path_like: str) -> str:
    """Convert an arbitrary artifact path to a single filesystem-safe
    segment for the attestation filename. Slashes → __, drop
    leading dots."""
    return path_like.lstrip(".").lstrip("/").replace("/", "__")


# ---------------------------------------------------------------------------
# Hash computation per artifact kind
# ---------------------------------------------------------------------------


def hash_artifact_file(path: Path) -> str:
    """For artifacts that live as files (state packet json, briefing,
    research artifact), hash the raw bytes."""
    return sha256_file(path)


def hash_artifact_json_object(obj: Any) -> str:
    """For artifacts derived from an in-memory object (task contract
    dict, manifest dict), hash the canonical JSON form."""
    return sha256_json(obj)


def hash_artifact_text(text: str) -> str:
    """For artifacts derived from text (markdown briefings, manifest
    md), hash the utf-8 encoding."""
    return sha256_text(text)


# ---------------------------------------------------------------------------
# Persistence
# ---------------------------------------------------------------------------


def attestations_dir(state_dir: Path) -> Path:
    return state_dir / "attestations"


def attestation_path_for(
    state_dir: Path,
    artifact_path: str,
) -> Path:
    """Canonical attestation file location for an artifact path."""
    return attestations_dir(state_dir) / f"{_safe_path_part(artifact_path)}.attest.json"


def write_attestation(
    state_dir: Path,
    attestation: Attestation,
) -> Path:
    """Persist an Attestation to disk atomically. Returns the path."""
    target = attestation_path_for(state_dir, attestation.artifact_path)
    target.parent.mkdir(parents=True, exist_ok=True)
    body = json.dumps(
        asdict(attestation),
        sort_keys=True,
        ensure_ascii=False,
        indent=2,
    ) + "\n"
    atomic_write_text(target, body)
    return target


def read_attestation(
    state_dir: Path,
    artifact_path: str,
) -> Attestation | None:
    """Read a previously-written attestation. Returns ``None`` when
    missing or malformed (caller decides whether to treat that as a
    hard error)."""
    target = attestation_path_for(state_dir, artifact_path)
    if not target.exists():
        return None
    try:
        data = json.loads(target.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    try:
        return Attestation(
            artifact_path=str(data.get("artifact_path", "") or ""),
            kind=str(data.get("kind", "") or ""),
            sha256=str(data.get("sha256", "") or ""),
            schema_version=str(
                data.get("schema_version", ATTESTATION_SCHEMA_VERSION)
                or ATTESTATION_SCHEMA_VERSION
            ),
            source_events=tuple(
                str(e) for e in (data.get("source_events") or [])
            ),
            task_id=str(data.get("task_id", "") or ""),
            dispatch_id=str(data.get("dispatch_id", "") or ""),
            attested_at=str(data.get("attested_at", "") or ""),
        )
    except (ValueError, TypeError):
        return None


# ---------------------------------------------------------------------------
# High-level attestation builders
# ---------------------------------------------------------------------------


def attest_file_artifact(
    state_dir: Path,
    *,
    artifact_path: Path,
    kind: str,
    source_events: tuple[str, ...] = (),
    task_id: str = "",
    dispatch_id: str = "",
) -> Attestation:
    """Hash a file-on-disk artifact and write its attestation."""
    digest = hash_artifact_file(artifact_path)
    attestation = Attestation(
        artifact_path=str(artifact_path),
        kind=kind,
        sha256=digest,
        source_events=source_events,
        task_id=task_id,
        dispatch_id=dispatch_id,
        attested_at=_now_iso(),
    )
    write_attestation(state_dir, attestation)
    return attestation


def attest_object_artifact(
    state_dir: Path,
    *,
    obj: Any,
    artifact_path: str,
    kind: str,
    source_events: tuple[str, ...] = (),
    task_id: str = "",
    dispatch_id: str = "",
) -> Attestation:
    """Hash an in-memory object (task contract / manifest dict) and
    write its attestation under a synthetic artifact_path
    identifier."""
    digest = hash_artifact_json_object(obj)
    attestation = Attestation(
        artifact_path=artifact_path,
        kind=kind,
        sha256=digest,
        source_events=source_events,
        task_id=task_id,
        dispatch_id=dispatch_id,
        attested_at=_now_iso(),
    )
    write_attestation(state_dir, attestation)
    return attestation


# ---------------------------------------------------------------------------
# Verification
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class VerificationResult:
    """Outcome of comparing a current artifact hash to its stored
    attestation."""

    matched: bool
    expected_sha256: str
    actual_sha256: str
    reason: str = ""

    @property
    def tampered(self) -> bool:
        return not self.matched and self.reason == "hash_mismatch"


def verify_file_artifact(
    state_dir: Path,
    *,
    artifact_path: Path,
) -> VerificationResult:
    """Check a file artifact against its stored attestation.

    Returns ``matched=True`` when the current SHA-256 equals the
    attestation. ``matched=False`` distinguishes:
    - ``reason="no_attestation"``: nothing on file
    - ``reason="missing_artifact"``: artifact file gone
    - ``reason="hash_mismatch"``: tampered / drifted
    """
    attestation = read_attestation(state_dir, str(artifact_path))
    if attestation is None:
        return VerificationResult(
            matched=False, expected_sha256="", actual_sha256="",
            reason="no_attestation",
        )
    if not artifact_path.exists():
        return VerificationResult(
            matched=False,
            expected_sha256=attestation.sha256,
            actual_sha256="",
            reason="missing_artifact",
        )
    actual = hash_artifact_file(artifact_path)
    if actual == attestation.sha256:
        return VerificationResult(
            matched=True,
            expected_sha256=attestation.sha256,
            actual_sha256=actual,
        )
    return VerificationResult(
        matched=False,
        expected_sha256=attestation.sha256,
        actual_sha256=actual,
        reason="hash_mismatch",
    )


def verify_object_artifact(
    state_dir: Path,
    *,
    obj: Any,
    artifact_path: str,
) -> VerificationResult:
    """Check an in-memory object against its stored attestation."""
    attestation = read_attestation(state_dir, artifact_path)
    if attestation is None:
        return VerificationResult(
            matched=False, expected_sha256="", actual_sha256="",
            reason="no_attestation",
        )
    actual = hash_artifact_json_object(obj)
    if actual == attestation.sha256:
        return VerificationResult(
            matched=True,
            expected_sha256=attestation.sha256,
            actual_sha256=actual,
        )
    return VerificationResult(
        matched=False,
        expected_sha256=attestation.sha256,
        actual_sha256=actual,
        reason="hash_mismatch",
    )
